apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: 559979279038.dkr.ecr.us-east-1.amazonaws.com/backend-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rds-secrets
              key: url

        - name: LLM_SERVER_URL
          value: "http://ollama-service:11434/v1" 

        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: api-key         
        - name: TAVILY_API_KEY
        
          valueFrom:
            secretKeyRef:
              name: tavily-secrets 
              key: api-key         

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: LoadBalancer