apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama-container
        image: 559979279038.dkr.ecr.us-east-1.amazonaws.com/ollama-custom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
        env:
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: bucket-name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-v3-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-v3-credentials
              key: secret-key
        # --- RECURSOS ESCASOS SIN GPU PARA PRUEBAS, EN REALIDAD HAY QUE PONERLE GPU, NO ESTOS RECURSOS QUE PUSIMOS ACÁ ---
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
            # nvidia.com/gpu: 1 # Hasta que AWS nos permita con GPU
            # nvidia.com/gpu: 1 