name: Build and Push ALL Images to ECR

on:
  push:
    branches:
      - main
    paths: 
      - 'backend/**'
      - 'frontend/**'
      - 'RAG_Airflow/**'
      - 'fine-tunning/**'
      - 'ollama_setup/**'

env:
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 1. AIRFLOW
      - name: Build & Push Airflow
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/ingesta-worker:latest ./worker_ingesta
          docker push ${{ steps.login-ecr.outputs.registry }}/ingesta-worker:latest

      # 2. WORKER INGESTA
 # 2. WORKER INGESTA
      - name: Build & Push Worker Ingesta
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/ingesta-worker:latest ./worker_ingesta
          docker push ${{ steps.login-ecr.outputs.registry }}/ingesta-worker:latest
      # 3. TRAIN WORKER
      - name: Build & Push Train Worker
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/train-worker:latest ./fine-tunning
          docker push ${{ steps.login-ecr.outputs.registry }}/train-worker:latest

      # 4. BACKEND
      - name: Build & Push Backend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/backend-api:latest ./backend
          docker push ${{ steps.login-ecr.outputs.registry }}/backend-api:latest

      # 5. FRONTEND
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/frontend-ui:latest ./frontend
          docker push ${{ steps.login-ecr.outputs.registry }}/frontend-ui:latest

      # 6. OLLAMA CUSTOM
      - name: Build & Push Ollama Custom
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/ollama-custom:latest ./ollama_setup
          docker push ${{ steps.login-ecr.outputs.registry }}/ollama-custom:latest

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurar acceso al Cluster EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name lostsys-cluster-dev

      # === PASO CRUCIAL PARA TUS SECRETOS ===
      - name: Crear archivo de secretos de Kubernetes
        run: |
          echo "${{ secrets.K8S_SECRETS }}" > infra/kubernetes/secrets.yaml

      - name: Aplicar Manifiestos de Kubernetes
        run: |
          # Aplicamos los secretos PRIMERO para que los pods no den error al nacer
          kubectl apply -f infra/kubernetes/secrets.yaml
          kubectl apply -f infra/kubernetes/policies.yaml
          
          # Aplicamos el resto
          kubectl apply -f infra/kubernetes/ollama.yaml
          kubectl apply -f infra/kubernetes/train_and_mlflow.yaml
          kubectl apply -f infra/kubernetes/fastapi.yaml
          kubectl apply -f infra/kubernetes/airflow.yaml
          kubectl apply -f infra/kubernetes/frontend.yaml # <--- ¡No te olvides del front!
          
          # Reinicio para asegurar la última imagen
          kubectl rollout restart deployment ollama-deployment
          kubectl rollout restart deployment fastapi-deployment